// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_missile
global.__objectDepths[1] = -300; // obj_control
global.__objectDepths[2] = 0; // obj_scale
global.__objectDepths[3] = 0; // obj_laser
global.__objectDepths[4] = -1000; // obj_minimap
global.__objectDepths[5] = 0; // obj_elaser
global.__objectDepths[6] = 0; // par_flyable
global.__objectDepths[7] = 0; // obj_explosion
global.__objectDepths[8] = 1; // obj_player
global.__objectDepths[9] = 0; // par_flyablesolid
global.__objectDepths[10] = -40000; // obj_cursor
global.__objectDepths[11] = 0; // par_enemy
global.__objectDepths[12] = -99999; // obj_ai
global.__objectDepths[13] = 0; // par_enemyobj
global.__objectDepths[14] = 0; // par_wall
global.__objectDepths[15] = 0; // par_obj
global.__objectDepths[16] = 0; // par_enemysolid
global.__objectDepths[17] = 0; // par_staticsolid
global.__objectDepths[18] = 0; // par_static
global.__objectDepths[19] = 0; // par_rack
global.__objectDepths[20] = 0; // par_ethrust
global.__objectDepths[21] = 0; // par_life
global.__objectDepths[22] = 0; // par_turret
global.__objectDepths[23] = 0; // obj_laser_control
global.__objectDepths[24] = 10; // obj_wall
global.__objectDepths[25] = 0; // obj_glass
global.__objectDepths[26] = 9; // obj_life
global.__objectDepths[27] = 0; // obj_zoom
global.__objectDepths[28] = 0; // obj_door
global.__objectDepths[29] = 0; // obj_doorcol
global.__objectDepths[30] = -5999; // obj_nav
global.__objectDepths[31] = 0; // par_thrust
global.__objectDepths[32] = 6; // obj_locker
global.__objectDepths[33] = 1; // obj_oxygen
global.__objectDepths[34] = -1; // obj_thrustleft
global.__objectDepths[35] = 6; // obj_reactor
global.__objectDepths[36] = -1; // obj_thrustright
global.__objectDepths[37] = -1; // obj_thrustup
global.__objectDepths[38] = 0; // obj_stone
global.__objectDepths[39] = -1; // obj_thrustdown
global.__objectDepths[40] = 0; // obj_dirt
global.__objectDepths[41] = 2; // obj_plat
global.__objectDepths[42] = -1; // obj_turret
global.__objectDepths[43] = -1; // obj_turretleft
global.__objectDepths[44] = -1; // obj_rackright
global.__objectDepths[45] = -2; // obj_stairs
global.__objectDepths[46] = -1; // obj_rackup
global.__objectDepths[47] = -1; // obj_turretdown
global.__objectDepths[48] = -1; // obj_rackdown
global.__objectDepths[49] = -1; // obj_rackleft
global.__objectDepths[50] = -2; // obj_stairs2
global.__objectDepths[51] = -2; // obj_stairs3
global.__objectDepths[52] = -2; // obj_stairs4
global.__objectDepths[53] = 5; // obj_bed
global.__objectDepths[54] = 5; // obj_enav
global.__objectDepths[55] = 6; // obj_gravgen
global.__objectDepths[56] = -2; // obj_metal
global.__objectDepths[57] = -2; // obj_emetal
global.__objectDepths[58] = -1; // obj_turretright
global.__objectDepths[59] = 10; // obj_ewall
global.__objectDepths[60] = -1; // obj_ethrustleft
global.__objectDepths[61] = -2; // obj_block
global.__objectDepths[62] = -1; // obj_ethrustup
global.__objectDepths[63] = -1; // obj_ethrustdown
global.__objectDepths[64] = 0; // obj_glasss
global.__objectDepths[65] = 10; // obj_walls
global.__objectDepths[66] = -1; // obj_ethrustright
global.__objectDepths[67] = -1; // obj_eturret
global.__objectDepths[68] = 0; // obj_doors
global.__objectDepths[69] = 0; // obj_turrets
global.__objectDepths[70] = 6; // obj_reactors
global.__objectDepths[71] = 6; // obj_beds
global.__objectDepths[72] = 10; // obj_lifes
global.__objectDepths[73] = 0; // obj_metals
global.__objectDepths[74] = 0; // par_con
global.__objectDepths[75] = 0; // obj_plats
global.__objectDepths[76] = 6; // obj_lockers
global.__objectDepths[77] = 0; // obj_repselected
global.__objectDepths[78] = 0; // par_rep
global.__objectDepths[79] = -110; // obj_replife
global.__objectDepths[80] = -110; // obj_repglass
global.__objectDepths[81] = -110; // obj_repwall
global.__objectDepths[82] = -110; // obj_repbed
global.__objectDepths[83] = -110; // obj_replocker
global.__objectDepths[84] = -110; // obj_repreactor
global.__objectDepths[85] = -110; // obj_repblock
global.__objectDepths[86] = -110; // obj_repgravgen
global.__objectDepths[87] = -110; // obj_rephalf
global.__objectDepths[88] = -110; // obj_repmetal
global.__objectDepths[89] = -110; // obj_repturret
global.__objectDepths[90] = -110; // obj_repthrust
global.__objectDepths[91] = 0; // obj_viewcontrol
global.__objectDepths[92] = -110; // obj_repstairs
global.__objectDepths[93] = 0; // obj_concontrol
global.__objectDepths[94] = -111; // obj_clear
global.__objectDepths[95] = -100; // obj_pallete
global.__objectDepths[96] = -110; // obj_repdoor
global.__objectDepths[97] = -111; // obj_load_mult
global.__objectDepths[98] = 0; // obj_conhud
global.__objectDepths[99] = -111; // obj_save_mult
global.__objectDepths[100] = -110; // obj_conmetal
global.__objectDepths[101] = -110; // obj_conblock
global.__objectDepths[102] = -110; // obj_conwall
global.__objectDepths[103] = -110; // obj_conglass
global.__objectDepths[104] = -110; // obj_condoor
global.__objectDepths[105] = -110; // obj_conlocker
global.__objectDepths[106] = -110; // obj_conturret
global.__objectDepths[107] = -110; // obj_conlife
global.__objectDepths[108] = -110; // obj_conrack
global.__objectDepths[109] = -110; // obj_conreactor
global.__objectDepths[110] = -110; // obj_conhalf
global.__objectDepths[111] = -110; // obj_congravgen
global.__objectDepths[112] = -110; // obj_conbed
global.__objectDepths[113] = -110; // obj_conplat
global.__objectDepths[114] = -110; // obj_conthruster
global.__objectDepths[115] = -301; // obj_invhold
global.__objectDepths[116] = -300; // obj_inv_1
global.__objectDepths[117] = 0; // obj_conselected
global.__objectDepths[118] = -110; // obj_constairs
global.__objectDepths[119] = -300; // obj_inv_3
global.__objectDepths[120] = -300; // obj_inv_5
global.__objectDepths[121] = 0; // obj_ast3
global.__objectDepths[122] = 0; // obj_ast4
global.__objectDepths[123] = -300; // obj_inv_4
global.__objectDepths[124] = -110; // obj_repplat
global.__objectDepths[125] = 0; // obj_ast5
global.__objectDepths[126] = -300; // obj_inv_locker
global.__objectDepths[127] = 0; // obj_ast6
global.__objectDepths[128] = 0; // obj_ast2
global.__objectDepths[129] = 0; // obj_ast8
global.__objectDepths[130] = 0; // obj_ast7
global.__objectDepths[131] = -300; // obj_inv_missile
global.__objectDepths[132] = 0; // obj_ast9
global.__objectDepths[133] = 0; // obj_ast12
global.__objectDepths[134] = 0; // obj_ast14
global.__objectDepths[135] = 0; // par_ast
global.__objectDepths[136] = 0; // obj_ast13
global.__objectDepths[137] = 0; // obj_pathside
global.__objectDepths[138] = 0; // par_path
global.__objectDepths[139] = -2; // obj_marker
global.__objectDepths[140] = 0; // obj_planet
global.__objectDepths[141] = 0; // obj_moon
global.__objectDepths[142] = 0; // par_generation
global.__objectDepths[143] = 0; // obj_ast11
global.__objectDepths[144] = 0; // obj_asteroid
global.__objectDepths[145] = -1; // obj_target
global.__objectDepths[146] = 0; // obj_fragright
global.__objectDepths[147] = -1; // obj_longdirt
global.__objectDepths[148] = 0; // obj_fragleft
global.__objectDepths[149] = -1; // obj_topdirts
global.__objectDepths[150] = 0; // obj_longstone
global.__objectDepths[151] = 0; // obj_stones
global.__objectDepths[152] = 0; // obj_terrain
global.__objectDepths[153] = -1; // obj_dirts
global.__objectDepths[154] = 0; // obj_ast10
global.__objectDepths[155] = 0; // obj_sun
global.__objectDepths[156] = 0; // obj_ast15
global.__objectDepths[157] = -2; // obj_half
global.__objectDepths[158] = -300; // obj_inv_2


global.__objectNames[0] = "obj_missile";
global.__objectNames[1] = "obj_control";
global.__objectNames[2] = "obj_scale";
global.__objectNames[3] = "obj_laser";
global.__objectNames[4] = "obj_minimap";
global.__objectNames[5] = "obj_elaser";
global.__objectNames[6] = "par_flyable";
global.__objectNames[7] = "obj_explosion";
global.__objectNames[8] = "obj_player";
global.__objectNames[9] = "par_flyablesolid";
global.__objectNames[10] = "obj_cursor";
global.__objectNames[11] = "par_enemy";
global.__objectNames[12] = "obj_ai";
global.__objectNames[13] = "par_enemyobj";
global.__objectNames[14] = "par_wall";
global.__objectNames[15] = "par_obj";
global.__objectNames[16] = "par_enemysolid";
global.__objectNames[17] = "par_staticsolid";
global.__objectNames[18] = "par_static";
global.__objectNames[19] = "par_rack";
global.__objectNames[20] = "par_ethrust";
global.__objectNames[21] = "par_life";
global.__objectNames[22] = "par_turret";
global.__objectNames[23] = "obj_laser_control";
global.__objectNames[24] = "obj_wall";
global.__objectNames[25] = "obj_glass";
global.__objectNames[26] = "obj_life";
global.__objectNames[27] = "obj_zoom";
global.__objectNames[28] = "obj_door";
global.__objectNames[29] = "obj_doorcol";
global.__objectNames[30] = "obj_nav";
global.__objectNames[31] = "par_thrust";
global.__objectNames[32] = "obj_locker";
global.__objectNames[33] = "obj_oxygen";
global.__objectNames[34] = "obj_thrustleft";
global.__objectNames[35] = "obj_reactor";
global.__objectNames[36] = "obj_thrustright";
global.__objectNames[37] = "obj_thrustup";
global.__objectNames[38] = "obj_stone";
global.__objectNames[39] = "obj_thrustdown";
global.__objectNames[40] = "obj_dirt";
global.__objectNames[41] = "obj_plat";
global.__objectNames[42] = "obj_turret";
global.__objectNames[43] = "obj_turretleft";
global.__objectNames[44] = "obj_rackright";
global.__objectNames[45] = "obj_stairs";
global.__objectNames[46] = "obj_rackup";
global.__objectNames[47] = "obj_turretdown";
global.__objectNames[48] = "obj_rackdown";
global.__objectNames[49] = "obj_rackleft";
global.__objectNames[50] = "obj_stairs2";
global.__objectNames[51] = "obj_stairs3";
global.__objectNames[52] = "obj_stairs4";
global.__objectNames[53] = "obj_bed";
global.__objectNames[54] = "obj_enav";
global.__objectNames[55] = "obj_gravgen";
global.__objectNames[56] = "obj_metal";
global.__objectNames[57] = "obj_emetal";
global.__objectNames[58] = "obj_turretright";
global.__objectNames[59] = "obj_ewall";
global.__objectNames[60] = "obj_ethrustleft";
global.__objectNames[61] = "obj_block";
global.__objectNames[62] = "obj_ethrustup";
global.__objectNames[63] = "obj_ethrustdown";
global.__objectNames[64] = "obj_glasss";
global.__objectNames[65] = "obj_walls";
global.__objectNames[66] = "obj_ethrustright";
global.__objectNames[67] = "obj_eturret";
global.__objectNames[68] = "obj_doors";
global.__objectNames[69] = "obj_turrets";
global.__objectNames[70] = "obj_reactors";
global.__objectNames[71] = "obj_beds";
global.__objectNames[72] = "obj_lifes";
global.__objectNames[73] = "obj_metals";
global.__objectNames[74] = "par_con";
global.__objectNames[75] = "obj_plats";
global.__objectNames[76] = "obj_lockers";
global.__objectNames[77] = "obj_repselected";
global.__objectNames[78] = "par_rep";
global.__objectNames[79] = "obj_replife";
global.__objectNames[80] = "obj_repglass";
global.__objectNames[81] = "obj_repwall";
global.__objectNames[82] = "obj_repbed";
global.__objectNames[83] = "obj_replocker";
global.__objectNames[84] = "obj_repreactor";
global.__objectNames[85] = "obj_repblock";
global.__objectNames[86] = "obj_repgravgen";
global.__objectNames[87] = "obj_rephalf";
global.__objectNames[88] = "obj_repmetal";
global.__objectNames[89] = "obj_repturret";
global.__objectNames[90] = "obj_repthrust";
global.__objectNames[91] = "obj_viewcontrol";
global.__objectNames[92] = "obj_repstairs";
global.__objectNames[93] = "obj_concontrol";
global.__objectNames[94] = "obj_clear";
global.__objectNames[95] = "obj_pallete";
global.__objectNames[96] = "obj_repdoor";
global.__objectNames[97] = "obj_load_mult";
global.__objectNames[98] = "obj_conhud";
global.__objectNames[99] = "obj_save_mult";
global.__objectNames[100] = "obj_conmetal";
global.__objectNames[101] = "obj_conblock";
global.__objectNames[102] = "obj_conwall";
global.__objectNames[103] = "obj_conglass";
global.__objectNames[104] = "obj_condoor";
global.__objectNames[105] = "obj_conlocker";
global.__objectNames[106] = "obj_conturret";
global.__objectNames[107] = "obj_conlife";
global.__objectNames[108] = "obj_conrack";
global.__objectNames[109] = "obj_conreactor";
global.__objectNames[110] = "obj_conhalf";
global.__objectNames[111] = "obj_congravgen";
global.__objectNames[112] = "obj_conbed";
global.__objectNames[113] = "obj_conplat";
global.__objectNames[114] = "obj_conthruster";
global.__objectNames[115] = "obj_invhold";
global.__objectNames[116] = "obj_inv_1";
global.__objectNames[117] = "obj_conselected";
global.__objectNames[118] = "obj_constairs";
global.__objectNames[119] = "obj_inv_3";
global.__objectNames[120] = "obj_inv_5";
global.__objectNames[121] = "obj_ast3";
global.__objectNames[122] = "obj_ast4";
global.__objectNames[123] = "obj_inv_4";
global.__objectNames[124] = "obj_repplat";
global.__objectNames[125] = "obj_ast5";
global.__objectNames[126] = "obj_inv_locker";
global.__objectNames[127] = "obj_ast6";
global.__objectNames[128] = "obj_ast2";
global.__objectNames[129] = "obj_ast8";
global.__objectNames[130] = "obj_ast7";
global.__objectNames[131] = "obj_inv_missile";
global.__objectNames[132] = "obj_ast9";
global.__objectNames[133] = "obj_ast12";
global.__objectNames[134] = "obj_ast14";
global.__objectNames[135] = "par_ast";
global.__objectNames[136] = "obj_ast13";
global.__objectNames[137] = "obj_pathside";
global.__objectNames[138] = "par_path";
global.__objectNames[139] = "obj_marker";
global.__objectNames[140] = "obj_planet";
global.__objectNames[141] = "obj_moon";
global.__objectNames[142] = "par_generation";
global.__objectNames[143] = "obj_ast11";
global.__objectNames[144] = "obj_asteroid";
global.__objectNames[145] = "obj_target";
global.__objectNames[146] = "obj_fragright";
global.__objectNames[147] = "obj_longdirt";
global.__objectNames[148] = "obj_fragleft";
global.__objectNames[149] = "obj_topdirts";
global.__objectNames[150] = "obj_longstone";
global.__objectNames[151] = "obj_stones";
global.__objectNames[152] = "obj_terrain";
global.__objectNames[153] = "obj_dirts";
global.__objectNames[154] = "obj_ast10";
global.__objectNames[155] = "obj_sun";
global.__objectNames[156] = "obj_ast15";
global.__objectNames[157] = "obj_half";
global.__objectNames[158] = "obj_inv_2";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for